language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: BfzPbixteaZqm/ot/0AgUNjT33Xi0IYcFacVR1CL9IVrh1eo9Rsvhm4Qc7n/sZTyvtMcQvg9xS5IAbWPz0ie5ecO7GcHSjPJ206yTiJ5am3K6ecbXbnSKBPsEfRQBNFgrOYDu83rb1nEo2tYw2Rt8Efu8oLdFGdNgIrgfL/+jSGEnEfXkw7pd2d+UShba42JqDhET4aiepx3M/IQeDUO4w3qjXWnp9yY1xAo7kvJI1a46kg/uPBo8jzJix66Ty9V5TEtgD262MYVUVop5gRLkiFHJgPgBHlf8i/k56RAP2UQ17SVuaSpfjYWqRY1PpgQv8yGvVEinwu5vl58a2lL2r/W2qa/6me0A265y2PLmEiT/ZWoFNMJnwy0vC4HP5My2vqHNbExfA/CKn6rLetiCFAMNu59XMiXRINpLr62gPeh43TGBt2fz0Ox7AMCha3l4/CQ5F3nWrIq/DYi2nYTYG/pqJYcbU90tFmDtPBxHkO0qGDZxquigXbhpYM4vnOfjkLxG7RdAbd/QnPpmQlJeWwgxsDuSYKDBytez8PqMaX/t2r6bg/z6+sPpo0TAn+r4jtOE/fpFddrthc3IIeVNWRSHrZKsNCUANCUYCPBMQ678XLJhJc0xlGrOFUOkTf5vlORI/s/GYqsiCQNVemX34fRJio1mLpYd8l/+Qbo8HM=
