language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
    secure: ls9zocVtp+Eml07TA5kbg6IEWWGQILcTDsqqGnaxGdWHbmMzeGxo/WJqEGa+5ftzua9Xkm3VcXaltFbW37WvP9papwLoCXgykSHqETP9RK0OFiJ9tvybTGdj1Yz5oW8Hnayq7FI0Yn412h/KyNvAZh4dKeRGX2gNPE/mv3+Lba/b85L+blcVEDNbne7F3KEVe17ALxrEa5xkfMUZLl7g7DCgblwKsnQF6bbUeZBVm2wmkp2x3YKalTHTcjIS7bwvkf9OpBgFlpQaDJgyE1xbiw+qqgXvGxRq04f6wMJOLlG4YpObNChmGKjhblnyJOydX4dqtcjuNgNhpAxEYml11s6T8q89TvIBvzB3gYdSSWSH9Md7RoCPVh+JJd2JKkg21XjlyelfVJuCUIxDoVR+ETiPmhY8y51gP5yugkmYKZxzZC9qN+mY5eq0T1paF9UismTvt+buL6JLmehCGaKFCVgGmE/NUrTR/Y7mn32/AX0MWjLfeDReMAaUgNkVSDJh1h+MQEIzhlPOzDVGKeVfKXofuW+UwljvKm/87LvtaTGkyGlbxuJcONicLb+7/mS2xhWypA80y/H4lPQTLZ+i1n8hf33bunujDA32bFDSApX7Cs8qAAQ2BDp7PYA3tjg7kA2knw8ItI5zeJejUba4ahj8S31gAOmKzCk8D1BLQsg=
